name: CI

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: [3.7]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@master

      - name: Setup python ${{ matrix.python_version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install requirements
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 solutions --count --show-source --statistics

      - name: Check type hints
        run: |
          pip install mypy
          mypy --ignore-missing-imports solutions

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=solutions --cov-report term-missing --cov-fail-under=100
