name: push

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: [3.7, 3.8]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@master

      - name: Setup python ${{ matrix.python_version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install requirements
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          pip install wemake-python-styleguide
          flake8 y* --count --show-source --statistics

      - name: pre-commit checks
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Check type hints
        run: |
          pip install mypy
          mypy --ignore-missing-imports .

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pytest --cov --cov-report term-missing --cov-fail-under=100
